Repository SOPT-all/35-COLLABORATION-ANDROID-CGV, pull requests merged in 2024-11, with the labels that each got.

#11 [Feature/#4] home UI 컴포넌트 구현
  app/build.gradle.kts
  app/src/main/java/org/sopt/cgv/core/common/extension/Modifier.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/CgvFooter.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/CgvMovieChartSection.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/CgvMySection.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/CgvPagerSection.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/CgvTopBar.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/ImageIndicator.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/MovieCard.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/MovieChart.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/MovieSmallCard.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/MyCgvComponent.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/ReservationButton.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/SectionHeader.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/TabBar.kt
  app/src/main/res/drawable/ic_12.xml
  app/src/main/res/drawable/ic_15.xml
  app/src/main/res/drawable/ic_19.xml
  app/src/main/res/drawable/ic_all.xml
  app/src/main/res/drawable/ic_divider.xml
  app/src/main/res/drawable/ic_home_arrow_down.xml
  app/src/main/res/drawable/ic_home_arrow_right.xml
  app/src/main/res/drawable/ic_home_footer_line.xml
  app/src/main/res/drawable/ic_home_like.xml
  app/src/main/res/drawable/ic_home_logo.xml
  app/src/main/res/drawable/ic_home_menu.xml
  app/src/main/res/drawable/ic_home_movie.xml
  app/src/main/res/drawable/ic_home_pen.xml
  app/src/main/res/drawable/ic_home_search.xml
  app/src/main/res/drawable/ic_home_ticket.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/img_99.png
  app/src/main/res/drawable/img_home_hot1.png
  app/src/main/res/drawable/img_home_hot2.png
  app/src/main/res/drawable/img_home_hot3.png
  app/src/main/res/drawable/img_home_hot4.png
  app/src/main/res/drawable/img_home_imax1.png
  app/src/main/res/drawable/img_home_imax2.png
  app/src/main/res/drawable/img_home_imax3.png
  app/src/main/res/drawable/img_home_imax4.png
  app/src/main/res/drawable/img_movie1.png
  app/src/main/res/drawable/img_movie2.png
  app/src/main/res/drawable/img_movie3.png
  app/src/main/res/drawable/img_movie4.png
  app/src/main/res/drawable/img_movie5.png
  app/src/main/res/drawable/img_movie6.png
  app/src/main/res/drawable/img_movie7.png
  app/src/main/res/drawable/img_movie8.png
  app/src/main/res/drawable/img_movie9.png
  app/src/main/res/drawable/img_special1.png
  app/src/main/res/drawable/img_special2.png
  app/src/main/res/drawable/img_special3.png
  gradle/libs.versions.toml
Labels: ui

#15 [Feature/#14] Cgv Button Component
  app/src/main/java/org/sopt/cgv/core/designsystem/component/button/CgvButton.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/MovieCard.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/MovieSmallCard.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/ReservationButton.kt
Labels: ui

#9 [Feature/#6] TimeScreen 극장 선택 모달 UI 구현
  app/src/main/java/org/sopt/cgv/core/common/extension/Modifier.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/CGVTab.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/ClickableVerticalRegionListInModal.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/SelectableTheatersInModal.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/TheaterClassificationTabInModal.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/TheaterSelectionModalBottomSheet.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/TheaterSelectionModalFooter.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreen.kt
  app/src/main/res/drawable/ic_time_modal_check.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ui, feature

#16 Feature/#13 seats screen UI
  app/build.gradle.kts
  app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
  app/src/main/java/org/sopt/cgv/core/designsystem/component/chip/Chip.kt
  app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectScreen.kt
  app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectViewModel.kt
  app/src/main/java/org/sopt/cgv/feature/seats/component/SeatConfirmationModal.kt
  app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionChangeButton.kt
  app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionChipRow.kt
  app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionConfirmRow.kt
  app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionModal1.kt
  app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionStepperRow.kt
  app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionTimeCardRow.kt
  app/src/main/java/org/sopt/cgv/feature/seats/component/SeatsScreenTopBar.kt
  app/src/main/java/org/sopt/cgv/feature/seats/component/Stepper.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_seats_minus.xml
  app/src/main/res/drawable/ic_seats_plus.xml
  app/src/main/res/drawable/ic_time_sun.xml
  app/src/main/res/drawable/img_seats1_selected.xml
  app/src/main/res/drawable/img_seats1_unselected.xml
  gradle/libs.versions.toml
Labels: ui, feature

#17 [Feature/#12] home route
  app/build.gradle.kts
  app/src/main/java/org/sopt/cgv/feature/home/HomeRoute.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/CgvFooter.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/CgvMovieChartSection.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/CgvMySection.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/CgvPagerSection.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/MovieCard.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/MovieChart.kt
  app/src/main/java/org/sopt/cgv/feature/home/component/TabBar.kt
  app/src/main/java/org/sopt/cgv/feature/home/data/HomeLocalData.kt
  app/src/main/java/org/sopt/cgv/feature/home/data/MovieItem.kt
  app/src/main/java/org/sopt/cgv/feature/home/data/MyCgvItem.kt
  app/src/main/java/org/sopt/cgv/feature/home/data/SpecialTheaterMovieItem.kt
  app/src/main/java/org/sopt/cgv/feature/main/MainActivity.kt
  app/src/main/res/drawable/img_home_ad1.png
  app/src/main/res/drawable/img_movie3.png
  app/src/main/res/drawable/img_movie4.png
  app/src/main/res/drawable/img_movie5.png
  app/src/main/res/drawable/img_movie6.png
  app/src/main/res/drawable/img_movie7.png
  app/src/main/res/drawable/img_movie8.png
  app/src/main/res/drawable/img_movie9.png
  app/src/main/res/drawable/img_today1.png
  app/src/main/res/drawable/img_today2.png
  app/src/main/res/drawable/img_today3.png
  gradle/libs.versions.toml
Labels: ui, feature

#24 [Feature/#22] TimeScreen에 api 연동
  app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
  app/src/main/java/org/sopt/cgv/feature/time/TimeScreenState.kt
  app/src/main/java/org/sopt/cgv/feature/time/TimeScreenViewModel.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/SelectableTheatersInModal.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/TheaterSelectionModalBottomSheet.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/TheaterSelectionModalFooter.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenAuditoriumAndTimeSelection.kt
  app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenTimeSelectionHeader.kt
  app/src/main/java/org/sopt/cgv/feature/time/data/CGVTimeTable.kt
  app/src/main/java/org/sopt/cgv/feature/time/data/MovieTheatersByDetailRegion.kt
  app/src/main/java/org/sopt/cgv/feature/time/data/Theaters.kt
  app/src/main/java/org/sopt/cgv/feature/time/data/TimeTable.kt
  app/src/main/java/org/sopt/cgv/network/ApiFactory.kt
  app/src/main/java/org/sopt/cgv/network/TimeService.kt
Labels: feature
